base_images:
  base:
    name: "4.3"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
images:
  - from: base
    to: sctptest
tag_specification:
  name: "4.3"
  namespace: ocp
promotion:
  name: "4.3"
  namespace: ocp
resources:
  "*":
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
  - as: e2e-tests
    commands: go get github.com/onsi/ginkgo/ginkgo && ginkgo -r
    openshift_installer_src:
      cluster_profile: gcp
