base_images:
  base:
    name: "4.3"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: release
    namespace: openshift
    tag: golang-1.13
images:
  - dockerfile_path: Dockerfile
    from: base
    to: fedetest
resources:
  "*":
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
  - as: e2e-tests
    commands: cd test && go test
    openshift_installer_src:
      cluster_profile: aws
